services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://program:test@db:5432/persons
    depends_on:
     db:
       condition: service_healthy
  db:
    container_name: postgres
    image: postgres
    restart: on-failure
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: persons
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
   db-data: