services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  person-service:
    image: uncledrema/person-service:latest
    container_name: person-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/persons"
    ports:
      - "9017:9017"
volumes:
  db-data: