server:
  port: 9017
spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5432/persons
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
