name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Run unit tests
        working-directory: ./person-service
        env:
          CI: true
        run: ./gradlew clean test --no-daemon

      - name: Docker Login (Docker Hub)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & publish image with bootBuildImage
        working-directory: ./person-service
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          # опционально: можно задать URL (если у вас в build.gradle указан)
          DOCKER_REGISTRY_URL: "https://index.docker.io/v1/"
        run: ./gradlew --no-daemon bootBuildImage --imageName=${{ secrets.DOCKERHUB_USERNAME }}/person-service:${{ github.sha }}

      - name: Push image to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/person-service:${{ github.sha }}
          echo "Pushing $IMAGE"
          docker push $IMAGE

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"